# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

format = """
$directory\
$git_branch\
$git_status\
$fill\
$rust\
$lua\
$python\
$nodejs\
$deno\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character
"""

[directory]
truncation_length = 3
truncation_symbol = ".../"

[fill]
symbol = " "

[git_branch]
symbol = " "

[git_status]
style = "yellow"

[rust]
symbol = " "
style = "cyan"
format = "[$symbol($version )]($style)"

[lua]
symbol = " "
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[cmd_duration]
min_time = 500
style = "grey"
format = "[$duration]($style)"

[jobs]
symbol = " "
style = "red"
number_threshold = 1
format = "[$symbol]($style)"

