# catppuccin-mocha.toml

[ansi]
ansi_00 = "#45475a"
ansi_01 = "#f38ba8"
ansi_02 = "#a6e3a1"
ansi_03 = "#f9e2af"
ansi_04 = "#89b4fa"
ansi_05 = "#f5c2e7"
ansi_06 = "#94e2d5"
ansi_07 = "#bac2de"
ansi_08 = "#585b70"
ansi_09 = "#f38ba8"
ansi_10 = "#a6e3a1"
ansi_11 = "#f9e2af"
ansi_12 = "#89b4fa"
ansi_13 = "#f5c2e7"
ansi_14 = "#94e2d5"
ansi_15 = "#a6adc8"

[ui]
background = "#1e1e2e"
foreground = "#cdd6f4"
cursor_color = "#f5e0dc"
cursor_text = "#1e1e2e"
selection_background = "#353749"
selection_foreground = "#cdd6f4"
wallpaper = "keyboard.png"

[nvim]
colorscheme = "catppuccin-mocha"

