# catppuccin-latte.toml

[ansi]
ansi_00 = "#5c5f77"
ansi_01 = "#d20f39"
ansi_02 = "#40a02b"
ansi_03 = "#df8e1d"
ansi_04 = "#1e66f5"
ansi_05 = "#ea76cb"
ansi_06 = "#179299"
ansi_07 = "#acb0be"
ansi_08 = "#6c6f85"
ansi_09 = "#d20f39"
ansi_10 = "#40a02b"
ansi_11 = "#df8e1d"
ansi_12 = "#1e66f5"
ansi_13 = "#ea76cb"
ansi_14 = "#179299"
ansi_15 = "#bcc0cc"

[ui]
background = "#eff1f5"
foreground = "#4c4f69"
cursor_color = "#dc8a78"
cursor_text = "#eff1f5"
selection_background = "#d8dae1"
selection_foreground = "#4c4f69"
wallpaper = "keyboard.png"

[nvim]
colorscheme = "catppuccin-latte"

