# kanso-zen.toml

[ansi]
ansi_00 = "#090E13"
ansi_01 = "#c4746e"
ansi_02 = "#8a9a7b"
ansi_03 = "#c4b28a"
ansi_04 = "#8ba4b0"
ansi_05 = "#a292a3"
ansi_06 = "#8ea4a2"
ansi_07 = "#c8c093"
ansi_08 = "#a4a7a4"
ansi_09 = "#e46876"
ansi_10 = "#87a987"
ansi_11 = "#e6c384"
ansi_12 = "#7fb4ca"
ansi_13 = "#938aa9"
ansi_14 = "#7aa89f"
ansi_15 = "#c5c9c7"

[ui]
background = "#090E13"
foreground = "#c5c9c7"
cursor     = "#c5c9c7"
selection_background = "#24262D"
selection_foreground = "#c5c9c7"
wallpaper = "clay-banks-fuji.jpg"

[nvim]
colorscheme = "kanso-zen"
