# rose-pine.toml

[ansi]
ansi_00 = "#26233a"
ansi_01 = "#eb6f92"
ansi_02 = "#31748f"
ansi_03 = "#f6c177"
ansi_04 = "#9ccfd8"
ansi_05 = "#c4a7e7"
ansi_06 = "#ebbcba"
ansi_07 = "#e0def4"
ansi_08 = "#6e6a86"
ansi_09 = "#eb6f92"
ansi_10 = "#31748f"
ansi_11 = "#f6c177"
ansi_12 = "#9ccfd8"
ansi_13 = "#c4a7e7"
ansi_14 = "#ebbcba"
ansi_15 = "#e0def4"

[ui]
background = "#191724"
foreground = "#e0def4"
cursor_color = "#e0def4"
selection_background = "#403d52"
selection_foreground = "#e0def4"
wallpaper = "macos-lion-fuji.jpg"

[nvim]
colorscheme = "rose-pine"

